version: "3"

volumes:
    # Databases data
    main_db_data:
    scraper_db_data:
    keycloack_db_data:
    # Services Data
    main_db_data:
    main_data:
    scraper_data:
    search_data:


services:
    keycloack_db:
        image: postgres:13-alpine
        restart: unless-stopped
        volumes:
            - keycloack_db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
    keycloak:
        image: quay.io/keycloak/keycloak:13.0.1
        restart: unless-stopped
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: keycloack_db
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: Pa55w0rd
        ports:
            - 8081:8080
        depends_on:
            - keycloack_db

    flora_db:
        image: postgres:13-alpine
        restart: unless-stopped
        volumes:
            - main_db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: flora
            POSTGRES_USER: flora
            POSTGRES_PASSWORD: password
        ports: 
            - 5432:5432

    scraper_db:
        image: postgres:13-alpine
        restart: unless-stopped
        volumes:
            - scraper_db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: scraper
            POSTGRES_USER: scraper
            POSTGRES_PASSWORD: password
        ports: 
            - 5431:5432

    meilisearch:
        image: getmeili/meilisearch:v0.20.0
        command: ./meilisearch --master-key=masterKey --no-analytics=true
        volumes: 
            - search_data:/data.ms
        ports:
            - 7700:7700
